#!/bin/bash
# ONNX GPU推理 - 快速命令参考

echo "════════════════════════════════════════════════════════════════"
echo "  HDVO ONNX GPU 推理 - 快速命令"
echo "════════════════════════════════════════════════════════════════"
echo ""

CONFIG="configs/hdvo/stereohdvo_posesup_coex_kittiodom_huberloss.py"
CHECKPOINT="work_dirs/stereohdvo_posesup_coex_kittiodom_huberloss/iter_40000.pth"

echo "1️⃣  ONNX CUDA Provider（推荐）"
echo "────────────────────────────────────────────────────────────────"
echo "OMP_NUM_THREADS=12 python tools/test.py \\"
echo "    $CONFIG \\"
echo "    $CHECKPOINT \\"
echo "    --launcher none \\"
echo "    --test_seq_id 09 \\"
echo "    --use-onnx \\"
echo "    --onnx-provider CUDAExecutionProvider"
echo ""

echo "2️⃣  ONNX TensorRT Provider + FP16（最快）"
echo "────────────────────────────────────────────────────────────────"  
echo "OMP_NUM_THREADS=12 python tools/test.py \\"
echo "    $CONFIG \\"
echo "    $CHECKPOINT \\"
echo "    --launcher none \\"
echo "    --test_seq_id 09 \\"
echo "    --use-onnx \\"
echo "    --onnx-provider TensorrtExecutionProvider \\"
echo "    --fp16"
echo ""

echo "3️⃣  完整测试（带评估）"
echo "────────────────────────────────────────────────────────────────"
echo "OMP_NUM_THREADS=12 python tools/test.py \\"
echo "    $CONFIG \\"
echo "    $CHECKPOINT \\"
echo "    --launcher none \\"
echo "    --eval EPE 3PE D1 \\"
echo "    --test_seq_id 09 \\"
echo "    --use-onnx \\"
echo "    --onnx-provider CUDAExecutionProvider"
echo ""

echo "4️⃣  自定义ONNX模型"
echo "────────────────────────────────────────────────────────────────"
echo "python tools/test.py \\"
echo "    $CONFIG \\"
echo "    $CHECKPOINT \\"
echo "    --use-onnx \\"
echo "    --onnx-model work_dirs/onnx_models/depth_net_optimized.onnx \\"
echo "    --onnx-provider CUDAExecutionProvider"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo "  对比：所有优化方案"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "PyTorch FP32（基准）:"
echo "  python tools/test.py $CONFIG $CHECKPOINT --test_seq_id 09"
echo ""
echo "PyTorch FP16:"
echo "  python tools/test.py $CONFIG $CHECKPOINT --test_seq_id 09 --fp16"
echo ""
echo "PyTorch FP16 + JIT:"
echo "  python tools/test.py $CONFIG $CHECKPOINT --test_seq_id 09 --fp16 --compile"
echo ""
echo "ONNX CUDA:"
echo "  python tools/test.py $CONFIG $CHECKPOINT --test_seq_id 09 --use-onnx --onnx-provider CUDAExecutionProvider"
echo ""
echo "ONNX TensorRT + FP16:"
echo "  python tools/test.py $CONFIG $CHECKPOINT --test_seq_id 09 --use-onnx --onnx-provider TensorrtExecutionProvider --fp16"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo "  注意事项"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "• 确保在 hdvo2 环境中运行: conda activate hdvo2"
echo "• TensorRT首次运行需要构建引擎（2-5分钟）"
echo "• 引擎缓存在 work_dirs/trt_cache/"
echo "• ONNX模型位于 work_dirs/onnx_models/depth_net.onnx"
echo ""
echo "详细文档:"
echo "  docs/ONNX_GPU_INTEGRATION.md"
echo "  docs/OPTIMIZATION_GUIDE.md"
echo "════════════════════════════════════════════════════════════════"
