MESSAGE(STATUS "\n_____ rox_open/cmake/platform/platform_linux.cmake ____________________________________________\n" )

# Detect architecture and set appropriate SIMD support
if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(aarch64|arm64|ARM64)")
   MESSAGE(STATUS "Detected ARM64 architecture")
   set(OPENROX_HAS_NEON_SUPPORT true)
   set(OPENROX_HAS_SSE_SUPPORT false)
   set(OPENROX_HAS_AVX_SUPPORT false)
   set(OPENROX_IS_MOBILE false)
   set(ARCH "arm64")
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(arm|ARM)")
   MESSAGE(STATUS "Detected ARM32 architecture")
   set(OPENROX_HAS_NEON_SUPPORT true)
   set(OPENROX_HAS_SSE_SUPPORT false)
   set(OPENROX_HAS_AVX_SUPPORT false)
   set(OPENROX_IS_MOBILE false)
   set(ARCH "arm")
else()
   MESSAGE(STATUS "Detected x86 architecture")
   set(OPENROX_HAS_NEON_SUPPORT false)
   set(OPENROX_HAS_SSE_SUPPORT true)
   set(OPENROX_HAS_AVX_SUPPORT true)
endif()

MESSAGE("OPENROX_HAS_NEON_SUPPORT : ${OPENROX_HAS_NEON_SUPPORT}")
MESSAGE("OPENROX_HAS_SSE_SUPPORT : ${OPENROX_HAS_SSE_SUPPORT}")
MESSAGE("OPENROX_HAS_AVX_SUPPORT : ${OPENROX_HAS_AVX_SUPPORT}")
MESSAGE("Architecture: ${ARCH}")

# Platform-specific settings
set(TARGET_PLATFORM "linux")
set(OPENROX_IS_LINUX true)
set(OPENROX_HAS_GUI_SUPPORT false)
set(OPENROX_HAS_MOVIE_SUPPORT false)
set(OPENROX_HAS_CAMERA_SUPPORT false)
set(OPENROX_HAS_STD_EXAMPLES_SUPPORT true)
set(OPENROX_HAS_STD_TESTS_SUPPORT true)
set(OPENROX_HAS_MAC_ADDR_SUPPORT false)
set(OPENROX_HAS_SHAREDSTATIC_SUPPORT "both")
set(OPENROX_HAS_OBJMODEL_SUPPORT true)
set(OPENROX_HAS_OPENMP_SUPPORT true)
set(OPENROX_HAS_GPROF_SUPPORT false)

# Define libraries
list(APPEND OPENROX_LICENCE_LIBS "")
list(APPEND OPENROX_EXTERNAL_LIBS "m" "pthread")
